In [1]:
import sys
import numpy as np


Basic Numpy Arrays

In [104]:
a = np.array([1, 2, 3, 4])

In [21]:
a[0]

1

In [105]:
a[:]

array([1, 2, 3, 4])

In [22]:
a[1:-1]

array([2, 3])

In [23]:
a[::2]

array([1, 3])

Array Types

check the data type of array

In [26]:
a.dtype

dtype('int32')

Lets take another list with combination of strings and ints
'<u11' is the subset of the string data type

In [27]:
b= np.array(["pandas", 1, -999, "Python"])
b.dtype

dtype('<U11')

Dimensions and shapes


In [36]:
array1 = np.array([[10,20,30],
                   [100,200,300], 
                   [1000,2000,3000]] )

In [34]:
array1.shape

(2, 3)

In [39]:
array1.ndim

2

In [40]:
array1.size

9

# 3  dimensional Array

In [41]:
array2 = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [42]:
array2

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [43]:
array2.shape

(2, 2, 3)

In [44]:
array2.ndim

3

In [45]:
array2.size

12

Indexing and slicing

In [47]:
index1 = np.array([
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [50]:
index1[0][2]

3

In [51]:
index1[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
index1[ 0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [58]:
index1[1:2, :2]

array([[4, 5]])

statistics

In [59]:
a = np.array([1, 2, 3, 4])

In [60]:
a.sum()

10

In [61]:
a.mean()

2.5

In [66]:
a.var()

1.25

In [68]:
s1.sum(axis=0) 

array([12, 15, 18])

In [67]:
s1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

axis=1 -- It's a column-wise operation
axis=1 -- It's a row-wise operation

In [72]:
s1.sum(axis=1) 

array([ 6, 15, 24])

Boolean arrays

arange() function is used for array creation.
 It requires three parameters: start, stop, and step. 

In [79]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [82]:
a[0], a[-2]

(0, 3)

In [83]:
a >= 2

array([False, False,  True,  True,  True])

In [84]:
a[a >= 2]

array([2, 3, 4])

In [85]:
a.mean()

2.0

In [ ]:
arrange function with start and stop

In [100]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

random.randint
Return random integers from low (inclusive) to high (exclusive).
random.randint(low, high=None, size=None, dtype=int)

arrange function with start, stop, step

In [101]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [91]:
random = np.random.randint(100, size = 5)
random

array([ 1, 87, 72, 40,  3])

In [92]:
random>70


array([False,  True,  True, False, False])

numpy.random.rand
random.rand(d0, d1, ..., dn)
Random values in a given shape
np.random.rand(1,3) -- 1 column 3 rows.

In [97]:
np.random.rand(1,3)

array([[0.84389962, 0.1155987 , 0.02009818]])

Vectorized operations


In [108]:
vo = np.arange(6)
vo

array([0, 1, 2, 3, 4, 5])

sum value of 10 to the entitred array

In [109]:
vo +10

array([10, 11, 12, 13, 14, 15])

In [117]:
vo

array([0, 1, 2, 3, 4, 5])

In [111]:

vo *10

array([ 0, 10, 20, 30, 40, 50])

In [115]:
vo1 = [60,70,80,90, 90, 100]

In [ ]:
when adding the two arrays, size should be same. otherwise it shows error as below

In [113]:
vo + vo1

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [118]:
vo

array([0, 1, 2, 3, 4, 5])

In [119]:
vo1

[60, 70, 80, 90, 90, 100]

In [116]:
vo + vo1

array([ 60,  71,  82,  93,  94, 105])

NumPy  Excercises

1. Create a numpy array of size 10, filled with zeros.

In [127]:
array_size = np.zeros(10)
array_size

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Create a numpy array with values ranging from 10 to 49

In [129]:
a= np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Create a numpy matrix of 3*2 float numbers, filled with ones.

In [134]:
np.ones([3,2], dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

4.Create a numpy array, filled with 3 random integer values between 1 and 10.

In [139]:
np.random.randint(10, size = 3)

array([7, 3, 1])

5.Create a numpy array with the odd numbers between 1 to 10s.

In [142]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Given the X numpy array, show it's first element

X = np.array(['A','B','C','D','E']
)

first element
last element
first three elements
all middle elements
elements in an odd position

In [145]:
X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [146]:
X[-1]

'E'

In [148]:
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [149]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [152]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

Logic functions
Given the X numpy array, return True if none of its elements is zer
all() -- True if ALL values in that column are True, otherwise False.
any() --  True if ANY value in that column is True, otherwise False.
Given the X numpy array, return True if none of its elements is zeroo

In [154]:
array = np.array([1, 0, -22, -1, 9, 8, 0.8])
array.all()

False

In [155]:
array = np.array([1, 0, -22, -1, 9, 8, 0.8])
array.any()

True